export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESSFULLY = 'ADD_PRODUCT_SUCCESSFULLY';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESSFULLY = 'GET_PRODUCTS_SUCCESSFULLY';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const DELETE_PRODUCT_ID = 'DELETE_PRODUCT_ID';
export const DELETE_PRODUCT_SUCCESSFULLY = 'DELETE_PRODUCT_SUCCESSFULLY';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const SET_EDIT = 'SET_EDIT';
export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT';
export const SET_EDIT_SUCCESSFULLY = 'SET_EDIT_SUCCESSFULLY';
export const SET_EDIT_ERROR = 'SET_EDIT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';