export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESSFULLY = 'ADD_PRODUCT_SUCCESSFULLY';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESSFULLY = 'GET_PRODUCTS_SUCCESSFULLY';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';